services:
  elastic:
    image: elasticsearch:8.5.3
    container_name: "elastic-query-bc-data"
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - es-net
  kibana:
    image: kibana:8.5.3
    container_name: "kibana-query-bc-data"
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200
    ports:
      - "5601:5601"
    networks:
      - es-net

networks:
  es-net: {}